application: my-first-project-153519
version: 1
runtime: python27
api_version: 1

handlers:
- url: /.*
  script: templates.py
threadsafe: false

libraries:
  - name: jinja2
    version: latest